name: 'Bug Report'
description: 'Report a bug to help us improve'

assignees:
  - 'pklaschka'

labels:
  - 'bug'

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the following form to help us fix it.
        
        Please describe the bug in as much detail as possible. If you have a screenshot or video of the bug, please attach it to this issue.
  - type: textarea
    id: bug-description
    validations:
      required: true
    attributes:
      label: 'Bug Description'
      description: 'Please described what happened.'
      placeholder: 'InDesign crashed after inserting a flag / I got an error message when trying to insert a flag / ...'
      render: 'markdown'
  - type: textarea
    id: bug-expected
    attributes:
        label: 'Expected behavior'
        description: 'Please describe what you expected to happen.'
        placeholder: 'The flag should have been inserted / The flag should have been inserted and the text should have been formatted / ...'
        render: 'markdown'
  - type: textarea
    id: bug-steps
    attributes:
        label: 'Steps to reproduce'
        description: 'Please describe the steps to reproduce the bug.'
        placeholder: '1. Open InDesign / 2. Insert a flag / 3. ...'
        render: 'markdown'
  - type: markdown
    attributes:
      value: |
        ## Additional Information
        Please fill out the following information to help us fix the bug.
  - type: dropdown
    id: os
    attributes:
      label: 'Operating System'
      description: 'Please select your operating system.'
      options:
        - 'Windows'
        - 'macOS'
  - type: input
    id: indesign-version
    attributes:
      label: 'InDesign Version'
      description: 'Please enter your InDesign version. You can find it in the "About InDesign" dialog (Help > About InDesign).'
      placeholder: '18.5 64 Bit'
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this bug. We will try to fix it as soon as possible.
